api_version = "2024-07"

[[extensions]]
name = "custom-field"
type = "ui_extension"
handle = "custom-field"
# [START custom-field.ext-config]
[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.shipping-option-list.render-after"
# [END custom-field.ext-config]
